name: Fetch accessions and start workflow
on:
  schedule:
    # Run every day at midnight -- except for today, let's just get the workflow going.
    - cron: '00 00 * * *'
  repository_dispatch:
jobs:
  fetch-accessions:
    name: Fetch
    runs-on: ubuntu-18.04
    # Check if the event is not triggered by a fork
    # Comment the next line if you want to get automated accession updates in your fork
    if: github.repository == 'galaxyproject/SARS-CoV-2'
    strategy:
      matrix:
        python-version: [3.8]
    defaults:
      run:
        shell: bash
        working-directory: ./genomics/4-Variation/
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Fetch sequence accessions
      run: ./fetch_sra_acc.sh
    - name: Install summary notebook dependencies
      run: pip install -r requirements.txt
      working-directory: ./genomics/4-Variation/updates/
    - name: Run summary notebook
      run: papermill metadata_stats.ipynb metadata_stats_rendered.ipynb
      working-directory: ./genomics/4-Variation/updates/
    - run: mv metadata_stats_rendered.ipynb metadata_stats.ipynb
      working-directory: ./genomics/4-Variation/updates/
    - name: Show differences
      run: 'git diff --stat'
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Update SARS-CoV-2 accessions"
        title: "Daily update of SARS-CoV-2 accessions"
        body: "Automated updates of SARS-CoV-2 accessions"
        labels: Automation
        branch: accession_updates
        base: master
  variation-workflow:
    if: github.repository == 'galaxyproject/SARS-CoV-2'
    name: Variation Workflow
    needs: fetch-accessions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    defaults:
      run:
        shell: bash
        working-directory: ./genomics/4-Variation/
    steps:
    - uses: actions/checkout@v2
      with:
        ref: accession_updates
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install workflow2executable
      run: pip install workflow2executable
    - name: Get todays llumina accessions
      run: grep -f <(grep $(date +%F) accession_and_date.tsv|cut -f1) current_illumina.txt > illumina_$(date +%F).txt || true
    - name: Trigger Galaxy Workflow on usegalaxy.org
      run: python covid_genome.py --accessions_file illumina_$(date +%F).txt --nc_45512_2_fasta_file NC_045512.2.fasta -n "$(date +%F) Update" --publish -g https://usegalaxy.org -a $GALAXY_API_KEY
      env:
        GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
    - name: Trigger Galaxy Workflow on usegalaxy.eu
      run: python covid_genome.py --accessions_file illumina_$(date +%F).txt --nc_45512_2_fasta_file NC_045512.2.fasta -n "$(date +%F) Update" --publish -g https://usegalaxy.eu -a $GALAXY_API_KEY
      env:
        GALAXY_API_KEY: ${{ secrets.GALAXY_EU_API_KEY }}
    - name: Trigger Galaxy Workflow on usegalaxy.fr
      run: python covid_genome.py --accessions_file illumina_$(date +%F).txt --nc_45512_2_fasta_file NC_045512.2.fasta -n "$(date +%F) Update" --publish -g https://usegalaxy.fr -a $GALAXY_API_KEY
      env:
        GALAXY_API_KEY: ${{ secrets.GALAXY_FR_API_KEY }}
